version: 2
updates:

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  allow:
  - dependency-type: "all"
  labels:
  - dependencies
  commit-message:
    prefix: "chore(deps)"
    prefix-development: "chore(deps-dev)"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - dependencies
  commit-message:
    prefix: "chore(deps)"
