name: Package

permissions:
  contents: read

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Need full history for version calculation in in ./utils/gitinfo.ts
          fetch-depth: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 'latest'
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Clean build directory
        run: pnpm run clean --output ${{ vars.OUTDIR }}
      - name: Build project
        run: pnpm run build --output ${{ vars.OUTDIR }}
      - name: Package extension
        run: pnpm run package --verbose --output ${{ vars.EXTENSION_NAME }}.zip ${{ vars.OUTDIR }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.EXTENSION_NAME }}.zip
          path: ${{ vars.EXTENSION_NAME }}.zip
          archive: false
