name: Code Validation

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-and-build:
    uses: ./.github/workflows/build-and-check.yml
    secrets: inherit
