name: Code Validation

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - '*'
  workflow_dispatch:

env:
  CACHE_DIRS: |
    ~/.npm

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Cache npm
      uses: actions/cache@v4
      with:
        path: ${{ env.CACHE_DIRS }}
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install dependencies
      run: npm ci
    - name: Lint files
      run: |
        npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Cache npm
      uses: actions/cache@v4
      with:
        path: ${{ env.CACHE_DIRS }}
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: |
        npm run build -- --output ${{ vars.OUTDIR }}
    - name: Package extension
      continue-on-error: true
      run: |
        npm run package -- --verbose --output ${{ vars.EXTENSION_FILENAME }} ${{ vars.OUTDIR }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ vars.EXTENSION_FILENAME }}
        path: ${{ vars.OUTDIR }}
